version: '3'
services:
  web:
    container_name: weather-radar
    build: .
    ports:
      - "3004:80"  # Change to map port 80 in the container to port 3001 on the host
    volumes:
      - .:/usr/share/nginx/html
